
version: 0.2

phases:
  # pre_build:
  #   commands:
  #     - ./build.sh seed
  build:
    commands:
      - chmod +x build.sh
      - ./build.sh int-test
      - ./build.sh deploy dev
      - ./build.sh acceptance-test
      - ./build.sh deploy prod
